((c-mode . ((indent-tabs-mode . nil)
            (tab-width . 4)
            ))
 (c++-mode . ((indent-tabs-mode . nil)
              (tab-width . 4)
              ))
 (nil . ((indent-tabs-mode . nil)
         (c-file-style . "stroustrup")
         (c-file-offsets
          . (quote ((innamespace . 0)
                    (inextern-lang . 0)
                    (inline-open . 0))))
         (c-basic-offset . 4)
         (fill-column . 80)
         ))
 )
